import React from 'react';
import {StyleSheet, Dimensions} from 'react-native';

// SetUp chiều cao
export const Height = StyleSheet.create({
    h1: {height: 10},
    h2: {height: 20},
    h3: {height: 30},
    h4: {height: 40},
    h5: {height: 50},
    h6: {height: 60},
    h7: {height: 70},
    h8: {height: 80},
    h9: {height: 90},
    h10: {height: 100},
    h15: {height: 150},
    h20: {height: 200},
    h25: {height: 250},
    h30: {height: 300},
    h40: {height: 400},
    h50: {height: 500},
    h60: {height: 600},
    h70: {height: 700},
    h80: {height: 800},
    h90: {height: 900},
    h100: {height: 1000},
    h_full: {height: Dimensions.get('window').height},
});
// SetUp Chiều dài
export const Width = StyleSheet.create({
    w1: {width: 10},
    w2: {width: 20},
    w3: {width: 30},
    w4: {width: 40},
    w5: {width: 50},
    w6: {width: 60},
    w7: {width: 70},
    w8: {width: 80},
    w9: {width: 90},
    w10: {width: 100},
    w15: {width: 150},
    w20: { width: 200},
    w25: { width: 250},
    w30: { width: 300},
    w40: { width: 400},
    w50: { width: 500},
    w60: { width: 600},
    w70: { width: 700},
    w80: { width: 800},
    w90: { width: 900},
    w100: { width: 1000},
    w_full: {width: Dimensions.get('window').width},
});
// Postion
export const Margin = StyleSheet.create({
    mt1: {marginTop: 1},
    mt2: {marginTop: 2},
    mt3: {marginTop: 3},
    mt4: {marginTop: 4},
    mt5: {marginTop: 5},
    mt6: {marginTop: 6},
    mt7: {marginTop: 7},
    mt8: {marginTop: 8},
    mt9: {marginTop: 9},
    mt10: {marginTop: 10},
    ml1: {marginLeft: 1},
    ml2: {marginLeft: 2},
    ml3: {marginLeft: 3},
    ml4: {marginLeft: 4},
    ml5: {marginLeft: 5},
    ml6: {marginLeft: 6},
    ml7: {marginLeft: 7},
    ml8: {marginLeft: 8},
    ml9: {marginLeft: 9},
    ml10: {marginLeft: 10},
    mr1: {marginRight: 1},
    mr2: {marginRight: 2},
    mr3: {marginRight: 3},
    mr4: {marginRight: 4},
    mr5: {marginRight: 5},
    mr6: {marginRight: 6},
    mr7: {marginRight: 7},
    mr8: {marginRight: 8},
    mr9: {marginRight: 9},
    mr10: {marginRight: 10},
    mb1: {marginBottom: 1},
    mb2: {marginBottom: 2},
    mb3: {marginBottom: 3},
    mb4: {marginBottom: 4},
    mb5: {marginBottom: 5},
    mb6: {marginBottom: 6},
    mb7: {marginBottom: 7},
    mb8: {marginBottom: 8},
    mb9: {marginBottom: 9},
    mb10: {marginBottom: 10},
    ms1: {marginStart: 1},
    ms2: {marginStart: 2},
    ms3: {marginStart: 3},
    ms4: {marginStart: 4},
    ms5: {marginStart: 5},
    ms6: {marginStart: 6},
    ms7: {marginStart: 7},
    ms8: {marginStart: 8},
    ms9: {marginStart: 9},
    ms10: {marginStart: 10},
    me1: {marginEnd: 1},
    me2: {marginEnd: 2},
    me3: {marginEnd: 3},
    me4: {marginEnd: 4},
    me5: {marginEnd: 5},
    me6: {marginEnd: 6},
    me7: {marginEnd: 7},
    me8: {marginEnd: 8},
    me9: {marginEnd: 9},
    me10: {marginEnd: 10},
})
// Paduning 
export const Padding = StyleSheet.create({
    pt1: {paddingTop: 100},
    pt2: {paddingTop: 2},
    pt3: {paddingTop: 3},
    pt4: {paddingTop: 4},
    pt5: {paddingTop: 5},
    pt6: {paddingTop: 6},
    pt7: {paddingTop: 7},
    pt8: {paddingTop: 8},
    pt9: {paddingTop: 9},
    pt10: {paddingTop: 1000},
    pl1: {paddingLeft: 1},
    pl2: {paddingLeft: 2},
    pl3: {paddingLeft: 3},
    pl4: {paddingLeft: 4},
    pl5: {paddingLeft: 5},
    pl6: {paddingLeft: 6},
    pl7: {paddingLeft: 7},
    pl8: {paddingLeft: 8},
    pl9: {paddingLeft: 9},
    pl10: {paddingLeft: 10},
    pr1: {paddingRight: 1},
    pr2: {paddingRight: 2},
    pr3: {paddingRight: 3},
    pr4: {paddingRight: 4},
    pr5: {paddingRight: 5},
    pr6: {paddingRight: 6},
    pr7: {paddingRight: 7},
    pr8: {paddingRight: 8},
    pr9: {paddingRight: 9},
    pr10: {paddingRight: 10},
    pb1: {paddingBottom: 1},
    pb2: {paddingBottom: 2},
    pb3: {paddingBottom: 3},
    pb4: {paddingBottom: 4},
    pb5: {paddingBottom: 5},
    pb6: {paddingBottom: 6},
    pb7: {paddingBottom: 7},
    pb8: {paddingBottom: 8},
    pb9: {paddingBottom: 9},
    pb10: {paddingBottom: 10},
    ps1: {paddingStart: 1},
    ps2: {paddingStart: 2},
    ps3: {paddingStart: 3},
    ps4: {paddingStart: 4},
    ps5: {paddingStart: 5},
    ps6: {paddingStart: 6},
    ps7: {paddingStart: 7},
    ps8: {paddingStart: 8},
    ps9: {paddingStart: 9},
    ps10: {paddingStart: 10},
    pe1: {paddingBottom: 1},
    pe2: {paddingBottom: 2},
    pe3: {paddingBottom: 3},
    pe4: {paddingBottom: 4},
    pe5: {paddingBottom: 5},
    pe6: {paddingBottom: 6},
    pe7: {paddingBottom: 7},
    pe8: {paddingBottom: 8},
    pe9: {paddingBottom: 9},
    pe10: {paddingBottom: 10},
})
// Position
export const Pos = StyleSheet.create({
    pos_r: {position: 'relative'},
    pos_a: {position: 'absolute'},
    t_1: {top: 1},
    t_2: {top: 2},
    t_3: {top: 3},
    t_4: {top: 4},
    t_5: {top: 5},
    t_6: {top: 6},
    t_7: {top: 7},
    t_8: {top: 8},
    t_9: {top: 9},
    t_10: {top: 10},
    l_1: {left: 1},
    l_2: {left: 2},
    l_3: {left: 3},
    l_4: {left: 4},
    l_5: {left: 5},
    l_6: {left: 6},
    l_7: {left: 7},
    l_8: {left: 8},
    l_9: {left: 9},
    l_10: {left: 10},
    r_1: {right: 1},
    r_2: {right: 2},
    r_3: {right: 3},
    r_4: {right: 4},
    r_5: {right: 5},
    r_6: {right: 6},
    r_7: {right: 7},
    r_8: {right: 8},
    r_9: {right: 9},
    r_10: {right: 10},
    b_1: {bottom: 1},
    b_2: {bottom: 2},
    b_3: {bottom: 3},
    b_4: {bottom: 4},
    b_5: {bottom: 5},
    b_6: {bottom: 6},
    b_7: {bottom: 7},
    b_8: {bottom: 8},
    b_9: {bottom: 9},
    b_10: {bottom: 10},
    t1: {top: 10},
    t2: {top: 20},
    t3: {top: 30},
    t4: {top: 40},
    t5: {top: 50},
    t6: {top: 60},
    t7: {top: 70},
    t8: {top: 80},
    t9: {top: 90},
    t10: {top: 100},
    l1: {left: 10},
    l2: {left: 20},
    l3: {left: 30},
    l4: {left: 40},
    l5: {left: 50},
    l6: {left: 60},
    l7: {left: 70},
    l8: {left: 80},
    l9: {left: 90},
    l10: {left: 100},
    r1: {right: 10},
    r2: {right: 20},
    r3: {right: 30},
    r4: {right: 40},
    r5: {right: 50},
    r6: {right: 60},
    r7: {right: 70},
    r8: {right: 80},
    r9: {right: 90},
    r10: {right: 100},
    b1: {bottom: 10},
    b2: {bottom: 20},
    b3: {bottom: 30},
    b4: {bottom: 40},
    b5: {bottom: 50},
    b6: {bottom: 60},
    b7: {bottom: 70},
    b8: {bottom: 80},
    b9: {bottom: 90},
    b10: {bottom: 100},
})
// Z-index
export const Zindex = StyleSheet.create({
    z1: {zIndex: 1},
    z2: {zIndex: 2},
    z3: {zIndex: 3},
    z4: {zIndex: 4},
    z5: {zIndex: 5},
    z6: {zIndex: 6},
    z7: {zIndex: 7},
    z8: {zIndex: 8},
    z9: {zIndex: 9},
    z10: {zIndex: 10},
})
// flexbox
export const Flex= StyleSheet.create({
    f1:{flex: 1},
    f2:{flex: 2},
    f3:{flex: 3},
    f4:{flex: 4},
    f5:{flex: 5},
    f6:{flex: 6},
    f7:{flex: 7},
    f8:{flex: 8},
    f9:{flex: 9},
    flexDirRow:{flexDirection: 'row'},
    flexDirCol:{flexDirection: 'column'},
    aliContentCenter:{alignContent:'center'},
    aliContentStart:{alignContent:'flex-start'},
    aliContentEnd:{alignContent:'flex-end'},
    aliContentSpaAround:{alignContent:'space-around'},
    aliContentSpaBetween:{alignContent:'space-between'},
    jusContentCenter:{justifyContent:'center'},
    jusContentStart:{justifyContent:'flex-start'},
    jusContentEnd:{justifyContent:'flex-end'},
    jusContentSpaAround:{justifyContent:'space-around'},
    jusContentSpaBetween:{justifyContent:'space-between'},
    jusContentSpaEven:{justifyContent:'space-evenly'},
    jusContentSpaEven:{justifyContent:'space-evenly'},
    aliItemStart: {alignItems: 'flex-start'},
    aliItemStretch: {alignItems: 'stretch'},
    aliItemEnd: {alignItems: 'flex-end'},
    aliItemCenter: {alignItems: 'center'},
    aliItemBaseline: {alignItems: 'baseline'},
    aliSelfStart: {alignSelf:'flex-start'},
    aliSelfEnd: {alignSelf:'flex-end'},
    aliSelfCenter: {alignSelf:'center'},
    aliSelfBaseline: {alignSelf:'baseline'},
    flexWrapNo:{flexWrap: 'nowrap'},
    flexWrapYes:{flexWrap: 'wrap'},
})
// Bodor width
export  const Font = StyleSheet.create({
    fw1: {fontWeight: '100'},
    fw2: {fontWeight: '200'},
    fw3: {fontWeight: '300'},
    fw4: {fontWeight: '400'},
    fw5: {fontWeight: '500'},
    fwNormal :{fontWeight: 'normal'},
    fwBold: {fontWeight: 'bold'},
});
export const BoderWidth = StyleSheet.create({
    boder_1: {borderWidth: 1},
    boder_2: {borderWidth: 2},
    boder_3: {borderWidth: 3},
    boder_4: {borderWidth: 4},
    boder_5: {borderWidth: 5},
});
// SetUp Thuộc tính Calc Height
export const HeightCalc = StyleSheet.create({
    hcalc1: {height: Dimensions.get('window').height -  10},
    hcalc2: {height: Dimensions.get('window').height -  20},
    hcalc3: {height: Dimensions.get('window').height -  30},
    hcalc4: {height: Dimensions.get('window').height -  40},
    hcalc5: {height: Dimensions.get('window').height -  50},
    hcalc6: {height: Dimensions.get('window').height -  60},
    hcalc7: {height: Dimensions.get('window').height -  70},
    hcalc8: {height: Dimensions.get('window').height -  80},
    hcalc9: {height: Dimensions.get('window').height -  90},
    hcalc10: {height: Dimensions.get('window').height -  100},
    hcalc15: {height: Dimensions.get('window').height -  150},
    hcalc20: {height: Dimensions.get('window').height -  200},
    hcalc30: {height: Dimensions.get('window').height -  300},
    hcalc40: {height: Dimensions.get('window').height -  400},
    hcalc50: {height: Dimensions.get('window').height -  500},
    hcalc60: {height: Dimensions.get('window').height -  600},
    hcalc70: {height: Dimensions.get('window').height -  700},
    hcalc80: {height: Dimensions.get('window').height -  800},
    hcalc90: {height: Dimensions.get('window').height -  900},
    hcalc100: {height: Dimensions.get('window').height -  1000},

});
// SetUp Thuộc tính calc Width
export const WidthCalc = StyleSheet.create({
    wcalc1: {width: Dimensions.get('window').width - 10},
    wcalc2: {width: Dimensions.get('window').width - 20},
    wcalc3: {width: Dimensions.get('window').width - 30},
    wcalc4: {width: Dimensions.get('window').width - 40},
    wcalc5: {width: Dimensions.get('window').width - 50},
    wcalc6: {width: Dimensions.get('window').width - 60},
    wcalc7: {width: Dimensions.get('window').width - 70},
    wcalc8: {width: Dimensions.get('window').width - 80},
    wcalc9: {width: Dimensions.get('window').width - 90},
    wcalc10: {width: Dimensions.get('window').width - 100},
    wcalc10: {width: Dimensions.get('window').width - 100},
    wcalc20: {width: Dimensions.get('window').width - 200},
    wcalc30: {width: Dimensions.get('window').width - 300},
    wcalc40: {width: Dimensions.get('window').width - 400},
    wcalc50: {width: Dimensions.get('window').width - 500},
    wcalc60: {width: Dimensions.get('window').width - 600},
    wcalc70: {width: Dimensions.get('window').width - 700},
    wcalc80: {width: Dimensions.get('window').width - 800},
    wcalc90: {width: Dimensions.get('window').width - 900},
    wcalc100: {width: Dimensions.get('window').width - 1000},
});
// SetUp Color
export const Colors = StyleSheet.create({
    aliceblue : {backgroundColor: '#f0f8ff'},
    antiquewhite : {backgroundColor: '#faebd7'},
    aqua : {backgroundColor: '#00ffff'},
    aquamarine : {backgroundColor: '#7fffd4'},
    azure : {backgroundColor: '#f0ffff'},
    beige : {backgroundColor: '#f5f5dc'},
    bisque : {backgroundColor: '#ffe4c4'},
    black : {backgroundColor: '#000000'},
    blanchedalmond : {backgroundColor: '#ffebcd'},
    blue : {backgroundColor: '#0000ff'},
    blueviolet : {backgroundColor: '#8a2be2'},
    brown : {backgroundColor: '#a52a2a'},
    burlywood : {backgroundColor: '#deb887'},
    cadetblue : {backgroundColor: '#5f9ea0'},
    chartreuse : {backgroundColor: '#7fff00'},
    chocolate : {backgroundColor: '#d2691e'},
    coral : {backgroundColor: '#ff7f50'},
    cornflowerblue : {backgroundColor: '#6495ed'},
    cornsilk : {backgroundColor: '#fff8dc'},
    crimson : {backgroundColor: '#dc143c'},
    cyan : {backgroundColor: '#00ffff'},
    darkblue : {backgroundColor: '#00008b'},
    darkcyan : {backgroundColor: '#008b8b'},
    darkgoldenrod : {backgroundColor: '#b8860b'},
    darkgray : {backgroundColor: '#a9a9a9'},
    darkgreen : {backgroundColor: '#006400'},
    darkgrey : {backgroundColor: '#a9a9a9'},
    darkkhaki : {backgroundColor: '#bdb76b'},
    darkmagenta : {backgroundColor: '#8b008b'},
    darkolivegreen : {backgroundColor: '#556b2f'},
    darkorange : {backgroundColor: '#ff8c00'},
    darkorchid : {backgroundColor: '#9932cc'},
    darkred : {backgroundColor: '#8b0000'},
    darksalmon : {backgroundColor: '#e9967a'},
    darkseagreen : {backgroundColor: '#8fbc8f'},
    darkslateblue : {backgroundColor: '#483d8b'},
    darkslategrey : {backgroundColor: '#2f4f4f'},
    darkturquoise : {backgroundColor: '#00ced1'},
    darkviolet : {backgroundColor: '#9400d3'},
    deeppink : {backgroundColor: '#ff1493'},
    deepskyblue : {backgroundColor: '#00bfff'},
    dimgray : {backgroundColor: '#696969'},
    dimgrey : {backgroundColor: '#696969'},
    dodgerblue : {backgroundColor: '#1e90ff'},
    firebrick : {backgroundColor: '#b22222'},
    floralwhite : {backgroundColor: '#fffaf0'},
    forestgreen : {backgroundColor: '#228b22'},
    fuchsia : {backgroundColor: '#ff00ff'},
    gainsboro : {backgroundColor: '#dcdcdc'},
    ghostwhite : {backgroundColor: '#f8f8ff'},
    gold : {backgroundColor: '#ffd700'},
    goldenrod : {backgroundColor: '#daa520'},
    gray : {backgroundColor: '#808080'},
    green : {backgroundColor: '#008000'},
    greenyellow : {backgroundColor: '#adff2f'},
    grey : {backgroundColor: '#808080'},
    honeydew : {backgroundColor: '#f0fff0'},
    hotpink : {backgroundColor: '#ff69b4'},
    indianred : {backgroundColor: '#cd5c5c'},
    indigo : {backgroundColor: '#4b0082'},
    ivory : {backgroundColor: '#fffff0'},
    khaki : {backgroundColor: '#f0e68c'},
    lavender : {backgroundColor: '#e6e6fa'},
    lavenderblush : {backgroundColor: '#fff0f5'},
    lawngreen : {backgroundColor: '#7cfc00'},
    lemonchiffon : {backgroundColor: '#fffacd'},
    lightblue : {backgroundColor: '#add8e6'},
    lightcoral : {backgroundColor: '#f08080'},
    lightcyan : {backgroundColor: '#e0ffff'},
    lightgoldenrodyellow : {backgroundColor: '#fafad2'},
    lightgray : {backgroundColor: '#d3d3d3'},
    lightgreen : {backgroundColor: '#90ee90'},
    lightgrey : {backgroundColor: '#d3d3d3'},
    lightpink : {backgroundColor: '#ffb6c1'},
    lightsalmon : {backgroundColor: '#ffa07a'},
    lightseagreen : {backgroundColor: '#20b2aa'},
    lightskyblue : {backgroundColor: '#87cefa'},
    lightslategrey : {backgroundColor: '#778899'},
    lightsteelblue : {backgroundColor: '#b0c4de'},
    lightyellow : {backgroundColor: '#ffffe0'},
    lime : {backgroundColor: '#00ff00'},
    limegreen : {backgroundColor: '#32cd32'},
    linen : {backgroundColor: '#faf0e6'},
    magenta : {backgroundColor: '#ff00ff'},
    maroon : {backgroundColor: '#800000'},
    mediumaquamarine : {backgroundColor: '#66cdaa'},
    mediumblue : {backgroundColor: '#0000cd'},
    mediumorchid : {backgroundColor: '#ba55d3'},
    mediumpurple : {backgroundColor: '#9370db'},
    mediumseagreen : {backgroundColor: '#3cb371'},
    mediumslateblue : {backgroundColor: '#7b68ee'},
    mediumspringgreen : {backgroundColor: '#00fa9a'},
    mediumturquoise : {backgroundColor: '#48d1cc'},
    mediumvioletred : {backgroundColor: '#c71585'},
    midnightblue : {backgroundColor: '#191970'},
    mintcream : {backgroundColor: '#f5fffa'},
    mistyrose : {backgroundColor: '#ffe4e1'},
    moccasin : {backgroundColor: '#ffe4b5'},
    navajowhite : {backgroundColor: '#ffdead'},
    navy : {backgroundColor: '#000080'},
    oldlace : {backgroundColor: '#fdf5e6'},
    olive : {backgroundColor: '#808000'},
    olivedrab : {backgroundColor: '#6b8e23'},
    orange : {backgroundColor: '#ffa500'},
    orangered : {backgroundColor: '#ff4500'},
    orchid : {backgroundColor: '#da70d6'},
    palegoldenrod : {backgroundColor: '#eee8aa'},
    palegreen : {backgroundColor: '#98fb98'},
    paleturquoise : {backgroundColor: '#afeeee'},
    palevioletred : {backgroundColor: '#db7093'},
    papayawhip : {backgroundColor: '#ffefd5'},
    peachpuff : {backgroundColor: '#ffdab9'},
    peru : {backgroundColor: '#cd853f'},
    pink : {backgroundColor: '#ffc0cb'},
    plum : {backgroundColor: '#dda0dd'},
    powderblue : {backgroundColor: '#b0e0e6'},
    purple : {backgroundColor: '#800080'},
    rebeccapurple : {backgroundColor: '#663399'},
    red : {backgroundColor: '#ff0000'},
    rosybrown : {backgroundColor: '#bc8f8f'},
    royalblue : {backgroundColor: '#4169e1'},
    saddlebrown : {backgroundColor: '#8b4513'},
    salmon : {backgroundColor: '#fa8072'},
    sandybrown : {backgroundColor: '#f4a460'},
    seagreen : {backgroundColor: '#2e8b57'},
    seashell : {backgroundColor: '#fff5ee'},
    sienna : {backgroundColor: '#a0522d'},
    silver : {backgroundColor: '#c0c0c0'},
    skyblue : {backgroundColor: '#87ceeb'},
    slateblue : {backgroundColor: '#6a5acd'},
    slategray : {backgroundColor: '#708090'},
    snow : {backgroundColor: '#fffafa'},
    springgreen : {backgroundColor: '#00ff7f'},
    steelblue : {backgroundColor: '#4682b4'},
    tan : {backgroundColor: '#d2b48c'},
    teal : {backgroundColor: '#008080'},
    thistle : {backgroundColor: '#d8bfd8'},
    tomato : {backgroundColor: '#ff6347'},
    turquoise : {backgroundColor: '#40e0d0'},
    violet : {backgroundColor: '#ee82ee'},
    wheat : {backgroundColor: '#f5deb3'},
    white : {backgroundColor: '#ffffff'},
    whitesmoke : {backgroundColor: '#f5f5f5'},
    yellow : {backgroundColor: '#ffff00'},
    yellowgreen : {backgroundColor: '#9acd32'},
});
export const BoderColor = StyleSheet.create({
    aliceblue : {borderColor: '#f0f8ff'},
    antiquewhite : {borderColor: '#faebd7'},
    aqua : {borderColor: '#00ffff'},
    aquamarine : {borderColor: '#7fffd4'},
    azure : {borderColor: '#f0ffff'},
    beige : {borderColor: '#f5f5dc'},
    bisque : {borderColor: '#ffe4c4'},
    black : {borderColor: '#000000'},
    blanchedalmond : {borderColor: '#ffebcd'},
    blue : {borderColor: '#0000ff'},
    blueviolet : {borderColor: '#8a2be2'},
    brown : {borderColor: '#a52a2a'},
    burlywood : {borderColor: '#deb887'},
    cadetblue : {borderColor: '#5f9ea0'},
    chartreuse : {borderColor: '#7fff00'},
    chocolate : {borderColor: '#d2691e'},
    coral : {borderColor: '#ff7f50'},
    cornflowerblue : {borderColor: '#6495ed'},
    cornsilk : {borderColor: '#fff8dc'},
    crimson : {borderColor: '#dc143c'},
    cyan : {borderColor: '#00ffff'},
    darkblue : {borderColor: '#00008b'},
    darkcyan : {borderColor: '#008b8b'},
    darkgoldenrod : {borderColor: '#b8860b'},
    darkgray : {borderColor: '#a9a9a9'},
    darkgreen : {borderColor: '#006400'},
    darkgrey : {borderColor: '#a9a9a9'},
    darkkhaki : {borderColor: '#bdb76b'},
    darkmagenta : {borderColor: '#8b008b'},
    darkolivegreen : {borderColor: '#556b2f'},
    darkorange : {borderColor: '#ff8c00'},
    darkorchid : {borderColor: '#9932cc'},
    darkred : {borderColor: '#8b0000'},
    darksalmon : {borderColor: '#e9967a'},
    darkseagreen : {borderColor: '#8fbc8f'},
    darkslateblue : {borderColor: '#483d8b'},
    darkslategrey : {borderColor: '#2f4f4f'},
    darkturquoise : {borderColor: '#00ced1'},
    darkviolet : {borderColor: '#9400d3'},
    deeppink : {borderColor: '#ff1493'},
    deepskyblue : {borderColor: '#00bfff'},
    dimgray : {borderColor: '#696969'},
    dimgrey : {borderColor: '#696969'},
    dodgerblue : {borderColor: '#1e90ff'},
    firebrick : {borderColor: '#b22222'},
    floralwhite : {borderColor: '#fffaf0'},
    forestgreen : {borderColor: '#228b22'},
    fuchsia : {borderColor: '#ff00ff'},
    gainsboro : {borderColor: '#dcdcdc'},
    ghostwhite : {borderColor: '#f8f8ff'},
    gold : {borderColor: '#ffd700'},
    goldenrod : {borderColor: '#daa520'},
    gray : {borderColor: '#808080'},
    green : {borderColor: '#008000'},
    greenyellow : {borderColor: '#adff2f'},
    grey : {borderColor: '#808080'},
    honeydew : {borderColor: '#f0fff0'},
    hotpink : {borderColor: '#ff69b4'},
    indianred : {borderColor: '#cd5c5c'},
    indigo : {borderColor: '#4b0082'},
    ivory : {borderColor: '#fffff0'},
    khaki : {borderColor: '#f0e68c'},
    lavender : {borderColor: '#e6e6fa'},
    lavenderblush : {borderColor: '#fff0f5'},
    lawngreen : {borderColor: '#7cfc00'},
    lemonchiffon : {borderColor: '#fffacd'},
    lightblue : {borderColor: '#add8e6'},
    lightcoral : {borderColor: '#f08080'},
    lightcyan : {borderColor: '#e0ffff'},
    lightgoldenrodyellow : {borderColor: '#fafad2'},
    lightgray : {borderColor: '#d3d3d3'},
    lightgreen : {borderColor: '#90ee90'},
    lightgrey : {borderColor: '#d3d3d3'},
    lightpink : {borderColor: '#ffb6c1'},
    lightsalmon : {borderColor: '#ffa07a'},
    lightseagreen : {borderColor: '#20b2aa'},
    lightskyblue : {borderColor: '#87cefa'},
    lightslategrey : {borderColor: '#778899'},
    lightsteelblue : {borderColor: '#b0c4de'},
    lightyellow : {borderColor: '#ffffe0'},
    lime : {borderColor: '#00ff00'},
    limegreen : {borderColor: '#32cd32'},
    linen : {borderColor: '#faf0e6'},
    magenta : {borderColor: '#ff00ff'},
    maroon : {borderColor: '#800000'},
    mediumaquamarine : {borderColor: '#66cdaa'},
    mediumblue : {borderColor: '#0000cd'},
    mediumorchid : {borderColor: '#ba55d3'},
    mediumpurple : {borderColor: '#9370db'},
    mediumseagreen : {borderColor: '#3cb371'},
    mediumslateblue : {borderColor: '#7b68ee'},
    mediumspringgreen : {borderColor: '#00fa9a'},
    mediumturquoise : {borderColor: '#48d1cc'},
    mediumvioletred : {borderColor: '#c71585'},
    midnightblue : {borderColor: '#191970'},
    mintcream : {borderColor: '#f5fffa'},
    mistyrose : {borderColor: '#ffe4e1'},
    moccasin : {borderColor: '#ffe4b5'},
    navajowhite : {borderColor: '#ffdead'},
    navy : {borderColor: '#000080'},
    oldlace : {borderColor: '#fdf5e6'},
    olive : {borderColor: '#808000'},
    olivedrab : {borderColor: '#6b8e23'},
    orange : {borderColor: '#ffa500'},
    orangered : {borderColor: '#ff4500'},
    orchid : {borderColor: '#da70d6'},
    palegoldenrod : {borderColor: '#eee8aa'},
    palegreen : {borderColor: '#98fb98'},
    paleturquoise : {borderColor: '#afeeee'},
    palevioletred : {borderColor: '#db7093'},
    papayawhip : {borderColor: '#ffefd5'},
    peachpuff : {borderColor: '#ffdab9'},
    peru : {borderColor: '#cd853f'},
    pink : {borderColor: '#ffc0cb'},
    plum : {borderColor: '#dda0dd'},
    powderblue : {borderColor: '#b0e0e6'},
    purple : {borderColor: '#800080'},
    rebeccapurple : {borderColor: '#663399'},
    red : {borderColor: '#ff0000'},
    rosybrown : {borderColor: '#bc8f8f'},
    royalblue : {borderColor: '#4169e1'},
    saddlebrown : {borderColor: '#8b4513'},
    salmon : {borderColor: '#fa8072'},
    sandybrown : {borderColor: '#f4a460'},
    seagreen : {borderColor: '#2e8b57'},
    seashell : {borderColor: '#fff5ee'},
    sienna : {borderColor: '#a0522d'},
    silver : {borderColor: '#c0c0c0'},
    skyblue : {borderColor: '#87ceeb'},
    slateblue : {borderColor: '#6a5acd'},
    slategray : {borderColor: '#708090'},
    snow : {borderColor: '#fffafa'},
    springgreen : {borderColor: '#00ff7f'},
    steelblue : {borderColor: '#4682b4'},
    tan : {borderColor: '#d2b48c'},
    teal : {borderColor: '#008080'},
    thistle : {borderColor: '#d8bfd8'},
    tomato : {borderColor: '#ff6347'},
    turquoise : {borderColor: '#40e0d0'},
    violet : {borderColor: '#ee82ee'},
    wheat : {borderColor: '#f5deb3'},
    white : {borderColor: '#ffffff'},
    whitesmoke : {borderColor: '#f5f5f5'},
    yellow : {borderColor: '#ffff00'},
    yellowgreen : {borderColor: '#9acd32'},
});
export const TextColor = StyleSheet.create({
    aliceblue : {color: '#f0f8ff'},
    antiquewhite : {color: '#faebd7'},
    aqua : {color: '#00ffff'},
    aquamarine : {color: '#7fffd4'},
    azure : {color: '#f0ffff'},
    beige : {color: '#f5f5dc'},
    bisque : {color: '#ffe4c4'},
    black : {color: '#000000'},
    blanchedalmond : {color: '#ffebcd'},
    blue : {color: '#0000ff'},
    blueviolet : {color: '#8a2be2'},
    brown : {color: '#a52a2a'},
    burlywood : {color: '#deb887'},
    cadetblue : {color: '#5f9ea0'},
    chartreuse : {color: '#7fff00'},
    chocolate : {color: '#d2691e'},
    coral : {color: '#ff7f50'},
    cornflowerblue : {color: '#6495ed'},
    cornsilk : {color: '#fff8dc'},
    crimson : {color: '#dc143c'},
    cyan : {color: '#00ffff'},
    darkblue : {color: '#00008b'},
    darkcyan : {color: '#008b8b'},
    darkgoldenrod : {color: '#b8860b'},
    darkgray : {color: '#a9a9a9'},
    darkgreen : {color: '#006400'},
    darkgrey : {color: '#a9a9a9'},
    darkkhaki : {color: '#bdb76b'},
    darkmagenta : {color: '#8b008b'},
    darkolivegreen : {color: '#556b2f'},
    darkorange : {color: '#ff8c00'},
    darkorchid : {color: '#9932cc'},
    darkred : {color: '#8b0000'},
    darksalmon : {color: '#e9967a'},
    darkseagreen : {color: '#8fbc8f'},
    darkslateblue : {color: '#483d8b'},
    darkslategrey : {color: '#2f4f4f'},
    darkturquoise : {color: '#00ced1'},
    darkviolet : {color: '#9400d3'},
    deeppink : {color: '#ff1493'},
    deepskyblue : {color: '#00bfff'},
    dimgray : {color: '#696969'},
    dimgrey : {color: '#696969'},
    dodgerblue : {color: '#1e90ff'},
    firebrick : {color: '#b22222'},
    floralwhite : {color: '#fffaf0'},
    forestgreen : {color: '#228b22'},
    fuchsia : {color: '#ff00ff'},
    gainsboro : {color: '#dcdcdc'},
    ghostwhite : {color: '#f8f8ff'},
    gold : {color: '#ffd700'},
    goldenrod : {color: '#daa520'},
    gray : {color: '#808080'},
    green : {color: '#008000'},
    greenyellow : {color: '#adff2f'},
    grey : {color: '#808080'},
    honeydew : {color: '#f0fff0'},
    hotpink : {color: '#ff69b4'},
    indianred : {color: '#cd5c5c'},
    indigo : {color: '#4b0082'},
    ivory : {color: '#fffff0'},
    khaki : {color: '#f0e68c'},
    lavender : {color: '#e6e6fa'},
    lavenderblush : {color: '#fff0f5'},
    lawngreen : {color: '#7cfc00'},
    lemonchiffon : {color: '#fffacd'},
    lightblue : {color: '#add8e6'},
    lightcoral : {color: '#f08080'},
    lightcyan : {color: '#e0ffff'},
    lightgoldenrodyellow : {color: '#fafad2'},
    lightgray : {color: '#d3d3d3'},
    lightgreen : {color: '#90ee90'},
    lightgrey : {color: '#d3d3d3'},
    lightpink : {color: '#ffb6c1'},
    lightsalmon : {color: '#ffa07a'},
    lightseagreen : {color: '#20b2aa'},
    lightskyblue : {color: '#87cefa'},
    lightslategrey : {color: '#778899'},
    lightsteelblue : {color: '#b0c4de'},
    lightyellow : {color: '#ffffe0'},
    lime : {color: '#00ff00'},
    limegreen : {color: '#32cd32'},
    linen : {color: '#faf0e6'},
    magenta : {color: '#ff00ff'},
    maroon : {color: '#800000'},
    mediumaquamarine : {color: '#66cdaa'},
    mediumblue : {color: '#0000cd'},
    mediumorchid : {color: '#ba55d3'},
    mediumpurple : {color: '#9370db'},
    mediumseagreen : {color: '#3cb371'},
    mediumslateblue : {color: '#7b68ee'},
    mediumspringgreen : {color: '#00fa9a'},
    mediumturquoise : {color: '#48d1cc'},
    mediumvioletred : {color: '#c71585'},
    midnightblue : {color: '#191970'},
    mintcream : {color: '#f5fffa'},
    mistyrose : {color: '#ffe4e1'},
    moccasin : {color: '#ffe4b5'},
    navajowhite : {color: '#ffdead'},
    navy : {color: '#000080'},
    oldlace : {color: '#fdf5e6'},
    olive : {color: '#808000'},
    olivedrab : {color: '#6b8e23'},
    orange : {color: '#ffa500'},
    orangered : {color: '#ff4500'},
    orchid : {color: '#da70d6'},
    palegoldenrod : {color: '#eee8aa'},
    palegreen : {color: '#98fb98'},
    paleturquoise : {color: '#afeeee'},
    palevioletred : {color: '#db7093'},
    papayawhip : {color: '#ffefd5'},
    peachpuff : {color: '#ffdab9'},
    peru : {color: '#cd853f'},
    pink : {color: '#ffc0cb'},
    plum : {color: '#dda0dd'},
    powderblue : {color: '#b0e0e6'},
    purple : {color: '#800080'},
    rebeccapurple : {color: '#663399'},
    red : {color: '#ff0000'},
    rosybrown : {color: '#bc8f8f'},
    royalblue : {color: '#4169e1'},
    saddlebrown : {color: '#8b4513'},
    salmon : {color: '#fa8072'},
    sandybrown : {color: '#f4a460'},
    seagreen : {color: '#2e8b57'},
    seashell : {color: '#fff5ee'},
    sienna : {color: '#a0522d'},
    silver : {color: '#c0c0c0'},
    skyblue : {color: '#87ceeb'},
    slateblue : {color: '#6a5acd'},
    slategray : {color: '#708090'},
    snow : {color: '#fffafa'},
    springgreen : {color: '#00ff7f'},
    steelblue : {color: '#4682b4'},
    tan : {color: '#d2b48c'},
    teal : {color: '#008080'},
    thistle : {color: '#d8bfd8'},
    tomato : {color: '#ff6347'},
    turquoise : {color: '#40e0d0'},
    violet : {color: '#ee82ee'},
    wheat : {color: '#f5deb3'},
    white : {color: '#ffffff'},
    whitesmoke : {color: '#f5f5f5'},
    yellow : {color: '#ffff00'},
    yellowgreen : {color: '#9acd32'},
});